#!/bin/sh
# bootstrap.sh — idempotent setup script for claude-assistant.
# Safe to run more than once.
set -e

REPO_DIR="$(cd "$(dirname "$0")" && pwd)"

# ── 1. Check required tools ────────────────────────────────────────────────────
for tool in node npm python3 claude; do
    if ! command -v "$tool" >/dev/null 2>&1; then
        echo "ERROR: '$tool' is not installed or not on PATH. Please install it and re-run." >&2
        exit 1
    fi
done
echo "node, npm, python3, claude found."

# Capture PATH now (while the user's full shell PATH is active) for use in
# the launchd plist, which runs with a minimal system PATH.
BOOTSTRAP_PATH="$PATH"

# ── 2. Create Python virtual environment ──────────────────────────────────────
if [ ! -d "$REPO_DIR/.venv" ]; then
    echo "Creating .venv..."
    python3 -m venv "$REPO_DIR/.venv"
else
    echo ".venv already exists, skipping creation."
fi

# ── 3. Install Python dependencies ────────────────────────────────────────────
echo "Installing Python dependencies..."
"$REPO_DIR/.venv/bin/pip" install --quiet -r "$REPO_DIR/requirements.txt"

# ── 4. Install Node dependencies (Playwright MCP) ─────────────────────────────
echo "Installing Node dependencies..."
(cd "$REPO_DIR" && npm install --silent)

# ── 5. Prompt for config values if config.yaml does not exist ─────────────────
if [ ! -f "$REPO_DIR/config.yaml" ]; then
    echo ""
    echo "=== Configuration ==="

    printf "VAULT_PATH — absolute path to your Obsidian vault root: "
    read -r VAULT_PATH

    printf "WRITE_VAULT — vault name for writes [Claude]: "
    read -r WRITE_VAULT
    WRITE_VAULT="${WRITE_VAULT:-Claude}"

    printf "RAG_URL — RAG server base URL [http://localhost:8000]: "
    read -r RAG_URL
    RAG_URL="${RAG_URL:-http://localhost:8000}"

    printf "CHROME_PROFILE — Chrome profile directory name [Profile 2]: "
    read -r CHROME_PROFILE
    CHROME_PROFILE="${CHROME_PROFILE:-Profile 2}"

    # ── 6. Write config.yaml ───────────────────────────────────────────────────
    cat > "$REPO_DIR/config.yaml" <<EOF
# config.yaml — claude-assistant runtime configuration
# Generated by bootstrap.sh. Do not commit to git.

vault_path: $VAULT_PATH
write_vault: $WRITE_VAULT
rag_url: $RAG_URL
chrome_profile: $CHROME_PROFILE
# Maximum concurrent Claude subprocesses. Playwright binds to a single Chrome
# profile, so keep this at 1 unless you configure multiple dedicated profiles.
max_concurrency: 1
repo_dir: $REPO_DIR
EOF
    echo "config.yaml written."
else
    echo "config.yaml already exists, skipping prompts."
    # Still need VAULT_PATH for creating the Requests directory below.
    VAULT_PATH="$(grep '^vault_path:' "$REPO_DIR/config.yaml" | sed 's/^vault_path:[[:space:]]*//')"
    WRITE_VAULT="$(grep '^write_vault:' "$REPO_DIR/config.yaml" | sed 's/^write_vault:[[:space:]]*//')"
    RAG_URL="$(grep '^rag_url:' "$REPO_DIR/config.yaml" | sed 's/^rag_url:[[:space:]]*//')"
    CHROME_PROFILE="$(grep '^chrome_profile:' "$REPO_DIR/config.yaml" | sed 's/^chrome_profile:[[:space:]]*//')"

    # Ensure repo_dir is up to date (handles repo moves)
    if ! grep -q "^repo_dir:" "$REPO_DIR/config.yaml"; then
        echo "repo_dir: $REPO_DIR" >> "$REPO_DIR/config.yaml"
    else
        # Update in place using a temp file (POSIX-portable)
        tmp="$REPO_DIR/config.yaml.tmp"
        sed "s|^repo_dir:.*|repo_dir: $REPO_DIR|" "$REPO_DIR/config.yaml" > "$tmp"
        mv "$tmp" "$REPO_DIR/config.yaml"
    fi
fi

# ── 7. Generate mcp_config.json ───────────────────────────────────────────────
echo "Generating mcp_config.json..."
sed \
    -e "s|{{REPO_DIR}}|$REPO_DIR|g" \
    -e "s|{{VAULT_PATH}}|$VAULT_PATH|g" \
    -e "s|{{WRITE_VAULT}}|$WRITE_VAULT|g" \
    -e "s|{{RAG_URL}}|$RAG_URL|g" \
    -e "s|{{CHROME_PROFILE}}|$CHROME_PROFILE|g" \
    "$REPO_DIR/mcp_config.json.template" > "$REPO_DIR/mcp_config.json"

# ── 8. Generate launchd plist ─────────────────────────────────────────────────
LAUNCH_AGENTS_DIR="$HOME/Library/LaunchAgents"
PLIST_PATH="$LAUNCH_AGENTS_DIR/com.claude-assistant.watcher.plist"
mkdir -p "$LAUNCH_AGENTS_DIR"
mkdir -p "$REPO_DIR/logs"

echo "Generating launchd plist at $PLIST_PATH..."
sed \
    -e "s|{{REPO_DIR}}|$REPO_DIR|g" \
    -e "s|{{BOOTSTRAP_PATH}}|$BOOTSTRAP_PATH|g" \
    "$REPO_DIR/launchd.plist.template" > "$PLIST_PATH"

# ── 9. Load launchd agent ─────────────────────────────────────────────────────
echo "Loading launchd agent..."
# Unload first if already loaded (idempotent); ignore errors if not loaded.
launchctl unload "$PLIST_PATH" 2>/dev/null || true
launchctl load "$PLIST_PATH"

# ── 10. Create Requests directory ─────────────────────────────────────────────
REQUESTS_DIR="$VAULT_PATH/Claude/Research/Requests"
if [ ! -d "$REQUESTS_DIR" ]; then
    mkdir -p "$REQUESTS_DIR"
    echo "Created $REQUESTS_DIR"
else
    echo "$REQUESTS_DIR already exists."
fi

# ── 11. Print summary ─────────────────────────────────────────────────────────
echo ""
echo "=== claude-assistant bootstrap complete ==="
echo "  Repo:          $REPO_DIR"
echo "  Vault:         $VAULT_PATH"
echo "  Write vault:   $WRITE_VAULT"
echo "  RAG URL:       $RAG_URL"
echo "  Chrome profile: $CHROME_PROFILE"
echo "  Requests dir:  $REQUESTS_DIR"
echo "  MCP config:    $REPO_DIR/mcp_config.json"
echo "  Plist:         $PLIST_PATH"
echo "  Logs:          $REPO_DIR/logs/"
echo ""
echo "The watcher is running. Drop a .md file into:"
echo "  $REQUESTS_DIR"
echo "to trigger a research request."
